//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Load_bank_files.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class newSb
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> TimeT { get; set; }
        public Nullable<System.DateTime> DateT { get; set; }
        public string Terminal { get; set; }
        public string Cardnum { get; set; }
        public string AutCode { get; set; }
        public string Sum { get; set; }
        public string Comis { get; set; }
        public string RRN { get; set; }
    }
}
