//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Load_bank_files.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class xlsx_baseEntities : DbContext
    {
        public xlsx_baseEntities()
            : base("name=xlsx_baseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bankBases> bankBases { get; set; }
        public virtual DbSet<gpb> gpb { get; set; }
        public virtual DbSet<newSb> newSb { get; set; }
        public virtual DbSet<vtb_bank> vtb_bank { get; set; }
    }
}
